name: Build AppImage

run-name: building appimage
on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: build appimage
      run: /bin/sh ./build_virtual_surround_manager.sh
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: AppImage
        path: dist
