name: Build AppImage

run-name: building appimage
on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/pkgforge-dev/archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Build AppImage
        run: /bin/sh ‎./dist/appimage/build_virtual_surround_manager.sh
      - uses: actions/upload-artifact@7.0.1
        with:
          name: AppImage
          path: ./build_appimage
